spring.application.name=PrimeiroProjeto

spring.datasource.url=jdbc:mysql://localhost:3306/banco_ninja?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# 3. Optional: SQL Logging (Highly recommended for development)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true